spring:
  application:
    name: clientes
  datasource:
    url: jdbc:postgresql://localhost:5555/icompraspedidos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

icompras:
  pedidos:
    clients:
      produtos:
        url: "http://localhost:8081/produtos"

      clients:
        url: "http://localhost:8082/clientes"
